require 'board'

RSpec.describe "Board" do

  let(:board) { Board.new('........
........
........
...BW...
...WB...
........
........
........
B') }

  it "Renders correnctly" do
    expected_output = '........
........
........
...BW...
...WB...
........
........
........
B'
    expect(board.to_s).to eq expected_output
  end

  it "Recognizes player turn" do
    expect(board.turn).to eq "B"
  end

  it "Reads chars at position" do
    char = board.char_at(Point.new(3, 3))
    expect(char).to eq "B"
  end

  it "Sets chars at position" do
    expected_output = '........
........
..0.....
...BW...
...WB...
........
........
........
B'
    board.set_char('0', Point.new(2, 2))
    char = board.char_at(Point.new(2, 2))
    expect(char).to eq "0"
    expect(board.to_s).to eq expected_output
  end

  it "Finds all positions of a specific char" do
    positions = board.all("B")
    expect(positions.count).to eq(2)
    expect(positions.include?(Point.new(3, 3))).to be_truthy
    expect(positions.include?(Point.new(4, 4))).to be_truthy
  end


end
